# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  slack-notification:
  
   runs-on: ubuntu-latest 
   needs: build
   if: ${{ always() }}
   steps:
    - name: Notify on Slack
      uses: voormedia/ci-slack-notification@main
      with:
        token: ${{ secrets.GH_CLONE_TOKE }}
        slack-webhook: ${{ secrets['T072MQT2QHE/B071Z4JTQ58/GhIgGwdvpBUHotjjAwjbiord'] }}    
      
  notify: 
   
    
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.JoltayBot }}
          to: ${{ secrets.Shelb0rne }}
          message: "Все работает"

   
